- hosts: all
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure FortiManager
    fortios_system_central_management:
      vdom:  "{{ vdom }}"
      system_central_management:
        central_management: "enable"
        ip: "10.210.63.104"
