- name: Copy Rapid7 to Host
  hosts: all
  tasks:
    - name: Copy rapid 7 install file
      become: true
      copy:
        src: /mnt/grenas01/Rapid7-Linux/agent_installer-x86_64.sh
        dest: /tmp/
        owner: root
        group: root
        mode: 0644
       register: rapid7
     - debug: msg="{{ rapid7.stdout }}"
     - debug: msg="{{ rapid7.stderr }}"
