- name: Copy Rapid7 to Host
  hosts: all
  become: false
  tasks:
     - name: Copy rapid 7 install file
       ansible.builtin.copy:
        src: agent_installer-x86_64.sh
        dest: /tmp/agent_installer-x86_64.sh
        owner: root
        mode: '0644'
     - name: change permissions rapid7
       command: chmod u+x agent_installer-x86_64.sh
     - name: Install Rapid7
       command: sudo ./agent_installer-x86_64.sh install_start --token us2:29adf8d8-a961-48a8-a43b-f1d6b5096252
       register: rapid7
     - debug: msg="{{ rapid7.stdout }}"
       
