- name: Copy Rapid7 to Host
  hosts: all
  tasks:
     - name: Copy rapid 7 install file
       copy:
        src: /mnt/grenas01/Rapid7-Linux/agent_installer-x86_64.sh
        dest: /tmp/
        owner: root
        group: root
        mode: 0644
