- name: Copy Rapid7 to Host
  hosts: all
  become: false
  tasks:
     - name: Copy rapid 7 install file
       ansible.builtin.copy:
        src: agent_installer-x86_64.sh
        dest: /tmp/agent_installer-x86_64.sh
        owner: root
        mode: '0644'
