- name: Install Rapid7 RHEL
  hosts: all
  become: true
  tasks:
     - name: Copy rapid 7 install file
       ansible.builtin.copy:
        src: rapid7-insight-agent-4.0.13.32-1.aarch64.rpm
        dest: /tmp/rapid7-insight-agent-4.0.13.32-1.aarch64.rpm
     - name: Install R7
       command: rpm -i /tmp/rapid7-insight-agent-4.0.13.32-1.aarch64.rpm
       register: Install
     - debug: msg="{{ Install.stdout }}"
     - name: CD to location
       command:  cd /opt/rapid7/ir_agent/components/insight_agent/4.0.13.32-1
       register: CD
     - debug: msg="{{ CD.stdout }}"
     - name: Configure R7
       command: ./configure_agent.sh --token us2:29adf8d8-a961-48a8-a43b-f1d6b5096252 --start
       register: Configure
     - debug: msg="{{ Configure.stdout }}"
       
