- name: Copy Rapid7 to Host
  hosts: all
  become: false
  tasks:
     - name: Copy rapid 7 install file
       ansible.builtin.copy:
        src: test.text
        dest: /etc/test.text
        owner: root
        mode: '0644'
