- name: Copy Rapid7 to Host
  hosts: all
  user: root
  tasks:
     - name: Copy rapid 7 install file
       copy:
        src: /tmp/agent_installer-x86_64.sh
        dest: /etc/
        owner: root
        group: root
        mode: 0644
