- name: Copy Rapid7 to Host
  hosts: all
  user: root
  tasks:
     - name: Copy rapid 7 install file
       copy:
        src: /mnt/Rapid7-Linux/agent_installer-x86_64.sh
        dest: /etc/
        remote_src: yes
