- name: Install Sophos
  hosts: all
  become: true
  tasks:
     - name: Copy Sophos Install file
       ansible.builtin.copy:
        src: SophosSetup.sh
        dest: /tmp/SophosSetup.sh
     - name: uninstall Sophos
       command: /tmp/SophosSetup.sh --uninstall-sav
       register: uninstall
     - debug: msg="{{ uninstall.stdout }}"
     - name: change permissions Sophos
       command: sudo chmod +x /tmp/SophosSetup.sh
     - name: Install Sophos
       command:  sudo /tmp/SophosSetup.sh
       register: install
     - debug: msg="{{ install.stdout }}"
