- name: Install Sophos
  hosts: grnp-ntp01.colehaan.net,grnp-ntp02.colehaan.net,grnp-ntp03.colehaan.net,somd-marc01.colehaan.net,somt-marc01.colehaan.net
  become: true
  tasks:
     - name: Copy Sophos Install file
       ansible.builtin.copy:
        src: SophosSetup.sh
        dest: /tmp/SophosSetup.sh
     #- name: uninstall Sophos
       #command: /opt/sophos-spl/bin/uninstall.sh
       #register: uninstall
     #- debug: msg="{{ uninstall.stdout }}"
     - name: change permissions Sophos
       command: sudo chmod +x /tmp/SophosSetup.sh
     - name: Install Sophos
       command:  sudo /tmp/SophosSetup.sh
       register: install
     - debug: msg="{{ install.stdout }}"
