- name: Red-hat updates
  hosts: all
  tasks:
     - name: Updating system
       command: wall updating system
     - name: Patching command
       command: yum -y update
       register: command_output
    - debug: msg="{{ command_output.stdout }}"
