- name: Red-hat updates
  hosts: all
  tasks:
     - name: Updating system
       command: wall updating system
       register: wall
     - debug: msg="{{ wall.stdout }}"
     - name: Patching command
       command: yum -y update
       register: update
    - debug: msg="{{ update.stdout }}"
